build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "building RELEASE $RELEASE"
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - >
      /kaniko/executor 
      --build-arg=RELEASE_KUBECTL=$RELEASE_KUBECTL 
      --build-arg=RELEASE_HELM=$RELEASE_HELM 
      --build-arg=RELEASE_KUSTOMIZE=$RELEASE_KUSTOMIZE 
      --context $CI_PROJECT_DIR 
      --dockerfile $CI_PROJECT_DIR/Dockerfile 
      --destination $CI_REGISTRY_IMAGE:${RELEASE_KUBECTL}_${RELEASE_KUSTOMIZE}_${RELEASE_HELM}
  parallel:
    matrix:
      - RELEASE_KUBECTL:
          - v1.22.2
          - v1.21.5
          - v1.20.11
        RELEASE_KUSTOMIZE:
          - v4.4.0
        RELEASE_HELM:
          - v3.7.1
